import struct

from common.serializer import (
    encode,
    decode,
    MSG_HELLO,
    MSG_CIPHERTEXT,
    MSG_DSA_PUBKEY,
    MSG_SIGNATURE,
    MSG_DONE,
    MSG_ERROR
)


# =====================================
# PROTOCOL CONFIGURATION
# =====================================

NONCE_SIZE = 32

DONE_CONFIRMATION_SIZE = 32


# =====================================
# INTERNAL HELPERS
# =====================================

def _require_bytes(
    value,
    field_name,
    minimum_size=0
):
    """
    Validate that a protocol field is bytes.
    """

    if not isinstance(
        value,
        bytes
    ):
        raise TypeError(
            f"{field_name} must be bytes"
        )

    if len(value) < minimum_size:
        raise ValueError(
            f"{field_name} is too short"
        )

    return value


def _require_exact_size(
    value,
    field_name,
    expected_size
):
    """
    Validate exact byte length.
    """

    _require_bytes(
        value,
        field_name
    )

    if len(value) != expected_size:
        raise ValueError(
            f"{field_name} must be "
            f"{expected_size} bytes, "
            f"got {len(value)}"
        )

    return value


# =====================================
# HELLO
# =====================================
#
# Payload:
#
# | 32-byte client nonce |
# | 4-byte KEM public key length |
# | KEM public key |
#
# =====================================

def build_hello(
    nonce: bytes,
    kem_public_key: bytes
) -> bytes:

    _require_exact_size(
        nonce,
        "HELLO nonce",
        NONCE_SIZE
    )

    _require_bytes(
        kem_public_key,
        "KEM public key",
        minimum_size=1
    )

    payload = (
        nonce
        +
        struct.pack(
            ">I",
            len(kem_public_key)
        )
        +
        kem_public_key
    )

    return encode(
        MSG_HELLO,
        payload
    )


# =====================================
# CIPHERTEXT
# =====================================
#
# Payload:
#
# | 32-byte server nonce |
# | 4-byte ciphertext length |
# | ciphertext |
#
# =====================================

def build_ciphertext(
    nonce: bytes,
    ciphertext: bytes
) -> bytes:

    _require_exact_size(
        nonce,
        "CIPHERTEXT nonce",
        NONCE_SIZE
    )

    _require_bytes(
        ciphertext,
        "KEM ciphertext",
        minimum_size=1
    )

    payload = (
        nonce
        +
        struct.pack(
            ">I",
            len(ciphertext)
        )
        +
        ciphertext
    )

    return encode(
        MSG_CIPHERTEXT,
        payload
    )


# =====================================
# DSA PUBLIC KEY
# =====================================
#
# Payload:
#
# | 4-byte public key length |
# | DSA public key |
#
# =====================================

def build_dsa_pubkey(
    dsa_public_key: bytes
) -> bytes:

    _require_bytes(
        dsa_public_key,
        "DSA public key",
        minimum_size=1
    )

    payload = (
        struct.pack(
            ">I",
            len(dsa_public_key)
        )
        +
        dsa_public_key
    )

    return encode(
        MSG_DSA_PUBKEY,
        payload
    )


# =====================================
# SIGNATURE
# =====================================
#
# Payload:
#
# | 4-byte signature length |
# | signature |
#
# =====================================

def build_signature(
    signature: bytes
) -> bytes:

    _require_bytes(
        signature,
        "Signature",
        minimum_size=1
    )

    payload = (
        struct.pack(
            ">I",
            len(signature)
        )
        +
        signature
    )

    return encode(
        MSG_SIGNATURE,
        payload
    )


# =====================================
# DONE
# =====================================
#
# Integrated format:
#
# | 32-byte PQ confirmation tag |
#
# The confirmation tag is generated by:
#
# HMAC-SHA256(
#     pq_shared_secret,
#     domain
#     || role
#     || auth_digest
#     || client_nonce
#     || server_nonce
# )
#
# =====================================

def build_done(
    confirmation: bytes
) -> bytes:

    _require_exact_size(
        confirmation,
        "DONE confirmation",
        DONE_CONFIRMATION_SIZE
    )

    return encode(
        MSG_DONE,
        confirmation
    )


# =====================================
# ERROR
# =====================================
#
# Payload:
#
# | UTF-8 encoded error message |
#
# =====================================

def build_error(
    message: str
) -> bytes:

    if not isinstance(
        message,
        str
    ):
        raise TypeError(
            "Error message must be str"
        )

    encoded_message = (
        message.encode(
            "utf-8"
        )
    )

    return encode(
        MSG_ERROR,
        encoded_message
    )


# =====================================
# PARSING HELPERS
# =====================================

def _parse_hello(
    payload: bytes
):
    """
    Parse HELLO payload.
    """

    minimum_size = (
        NONCE_SIZE
        +
        4
    )

    if len(payload) < minimum_size:
        raise ValueError(
            "Malformed HELLO payload"
        )

    nonce = payload[
        :NONCE_SIZE
    ]

    key_length = struct.unpack(
        ">I",
        payload[
            NONCE_SIZE:
            NONCE_SIZE + 4
        ]
    )[0]

    key_start = (
        NONCE_SIZE
        +
        4
    )

    key_end = (
        key_start
        +
        key_length
    )

    if key_length <= 0:
        raise ValueError(
            "Invalid KEM public key length"
        )

    if key_end != len(payload):
        raise ValueError(
            "HELLO KEM public key "
            "length mismatch"
        )

    kem_public_key = payload[
        key_start:
        key_end
    ]

    return {
        "nonce":
            nonce,

        "kem_public_key":
            kem_public_key
    }


def _parse_ciphertext(
    payload: bytes
):
    """
    Parse CIPHERTEXT payload.
    """

    minimum_size = (
        NONCE_SIZE
        +
        4
    )

    if len(payload) < minimum_size:
        raise ValueError(
            "Malformed CIPHERTEXT payload"
        )

    nonce = payload[
        :NONCE_SIZE
    ]

    ciphertext_length = struct.unpack(
        ">I",
        payload[
            NONCE_SIZE:
            NONCE_SIZE + 4
        ]
    )[0]

    ciphertext_start = (
        NONCE_SIZE
        +
        4
    )

    ciphertext_end = (
        ciphertext_start
        +
        ciphertext_length
    )

    if ciphertext_length <= 0:
        raise ValueError(
            "Invalid ciphertext length"
        )

    if ciphertext_end != len(payload):
        raise ValueError(
            "CIPHERTEXT length mismatch"
        )

    ciphertext = payload[
        ciphertext_start:
        ciphertext_end
    ]

    return {
        "nonce":
            nonce,

        "ciphertext":
            ciphertext
    }


def _parse_dsa_pubkey(
    payload: bytes
):
    """
    Parse DSA public key payload.
    """

    if len(payload) < 4:
        raise ValueError(
            "Malformed DSA_PUBKEY payload"
        )

    key_length = struct.unpack(
        ">I",
        payload[:4]
    )[0]

    if key_length <= 0:
        raise ValueError(
            "Invalid DSA public key length"
        )

    key_start = 4

    key_end = (
        key_start
        +
        key_length
    )

    if key_end != len(payload):
        raise ValueError(
            "DSA public key "
            "length mismatch"
        )

    dsa_public_key = payload[
        key_start:
        key_end
    ]

    return {
        "dsa_public_key":
            dsa_public_key
    }


def _parse_signature(
    payload: bytes
):
    """
    Parse signature payload.
    """

    if len(payload) < 4:
        raise ValueError(
            "Malformed SIGNATURE payload"
        )

    signature_length = struct.unpack(
        ">I",
        payload[:4]
    )[0]

    if signature_length <= 0:
        raise ValueError(
            "Invalid signature length"
        )

    signature_start = 4

    signature_end = (
        signature_start
        +
        signature_length
    )

    if signature_end != len(payload):
        raise ValueError(
            "SIGNATURE length mismatch"
        )

    signature = payload[
        signature_start:
        signature_end
    ]

    return {
        "signature":
            signature
    }


def _parse_done(
    payload: bytes
):
    """
    Parse DONE key-confirmation payload.
    """

    if len(payload) != DONE_CONFIRMATION_SIZE:
        raise ValueError(
            "DONE confirmation must be "
            f"{DONE_CONFIRMATION_SIZE} bytes, "
            f"got {len(payload)}"
        )

    return {
        "confirmation":
            payload,

        # Compatibility with your
        # handshake extraction helper.
        "payload":
            payload
    }


def _parse_error(
    payload: bytes
):
    """
    Parse UTF-8 error payload.
    """

    try:

        error_message = payload.decode(
            "utf-8"
        )

    except UnicodeDecodeError as exc:

        raise ValueError(
            "Malformed ERROR payload"
        ) from exc

    return {
        "error":
            error_message
    }


# =====================================
# MAIN PACKET PARSER
# =====================================

def parse_packet(
    raw_packet: bytes
):
    """
    Decode a protocol packet and return:

        (
            msg_type,
            fields
        )

    The outer serializer validates:
        - message type
        - payload length

    This function validates:
        - message-specific structure
        - exact field boundaries
        - required lengths
    """

    msg_type, payload = decode(
        raw_packet
    )

    # =====================================
    # HELLO
    # =====================================

    if msg_type == MSG_HELLO:

        fields = _parse_hello(
            payload
        )

    # =====================================
    # CIPHERTEXT
    # =====================================

    elif msg_type == MSG_CIPHERTEXT:

        fields = _parse_ciphertext(
            payload
        )

    # =====================================
    # DSA PUBLIC KEY
    # =====================================

    elif msg_type == MSG_DSA_PUBKEY:

        fields = _parse_dsa_pubkey(
            payload
        )

    # =====================================
    # SIGNATURE
    # =====================================

    elif msg_type == MSG_SIGNATURE:

        fields = _parse_signature(
            payload
        )

    # =====================================
    # DONE
    # =====================================

    elif msg_type == MSG_DONE:

        fields = _parse_done(
            payload
        )

    # =====================================
    # ERROR
    # =====================================

    elif msg_type == MSG_ERROR:

        fields = _parse_error(
            payload
        )

    # =====================================
    # DEFENSIVE FALLBACK
    # =====================================

    else:

        raise ValueError(
            f"Unsupported message type: "
            f"{msg_type:#04x}"
        )

    return (
        msg_type,
        fields
    )